name: Minishell CI

on:
  push:
    branches:
      - main
      - story
  pull_request:
    branches:
      - main
      - story

permissions:
  contents: read

jobs:
  norminette:
    name: Norminette Check
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: Norminette 설치
        run: python3 -m pip install norminette==3.3.50

      - name: Norm 검사
        run: norminette Assignments

  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: readline 설치
        run: sudo apt-get update && sudo apt-get install -y libreadline-dev

      - name: make 확인
        run: make -C Assignments fclean && make -C Assignments

      - name: 통합 테스트
        run: make -C Tests integration
